title: My first Git blog
author: Rikanda
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Trainig Git blog about psychology

# social links
twitter_username: No # DO NOT include the @ character, or else the build will fail!
github_username:  Rikanda # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
